import { expect } from "chai";
import { ethers } from "hardhat";
import { loadFixture } from "@nomicfoundation/hardhat-toolbox/network-helpers";
import { CarryTradeVault, MockXcm } from "../typechain-types";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

const XCM_PRECOMPILE_ADDR = "0x00000000000000000000000000000000000a0000";
const DOT = (n: number) => ethers.parseEther(n.toString()); // 18-decimal units

// Dummy call bytes (real bytes generated by scripts/generateCallBytes.ts)
const BIFROST_CALL  = ethers.hexlify(ethers.toUtf8Bytes("bifrost_slpx_mint_call"));
const HYDRATION_CALL = ethers.hexlify(ethers.toUtf8Bytes("hydration_router_sell_call"));
const SUBSTRATE_ACCOUNT = ethers.zeroPadValue(ethers.toBeHex(1234567890), 32);
// Dummy AssetHub sovereign account (real value: blake2_256("sibl" ++ LE(1000)))
const ASSET_HUB_SOVEREIGN = ethers.zeroPadValue(ethers.toBeHex(9999999), 32);

// ─────────────────────────────────────────────────────────────────────────────
// Fixture
// ─────────────────────────────────────────────────────────────────────────────

async function deployFixture() {
  const [owner, alice, bob] = await ethers.getSigners();

  // 1. Deploy MockXcm and place it at the XCM precompile address
  const MockXcmFactory = await ethers.getContractFactory("MockXcm");
  const mockXcm = await MockXcmFactory.deploy();
  await mockXcm.waitForDeployment();

  const mockXcmCode = await ethers.provider.getCode(await mockXcm.getAddress());
  await ethers.provider.send("hardhat_setCode", [XCM_PRECOMPILE_ADDR, mockXcmCode]);
  const xcm = MockXcmFactory.attach(XCM_PRECOMPILE_ADDR) as MockXcm;

  // 2. Deploy CarryTradeVault with 30% hedge ratio
  const VaultFactory = await ethers.getContractFactory("CarryTradeVault");
  const vault = await VaultFactory.deploy(3000) as CarryTradeVault;
  await vault.waitForDeployment();

  // 3. Pre-configure call templates, substrate account, and AssetHub sovereign
  await vault.setCallTemplates(BIFROST_CALL, HYDRATION_CALL);
  await vault.setVaultSubstrateAccount(SUBSTRATE_ACCOUNT);
  await vault.setAssetHubSovereign(ASSET_HUB_SOVEREIGN);

  return { vault, xcm, owner, alice, bob };
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

describe("CarryTradeVault", () => {
  // ── Deployment ─────────────────────────────────────────────────────────────

  describe("Deployment", () => {
    it("sets correct initial state", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      expect(await vault.state()).to.equal(0); // IDLE
      expect(await vault.hedgeRatioBps()).to.equal(3000);
      expect(await vault.totalDeposited()).to.equal(0);
      expect(await vault.totalShares()).to.equal(0);
      expect(await vault.owner()).to.equal(owner.address);
    });

    it("rejects hedge ratio above 50%", async () => {
      const VaultFactory = await ethers.getContractFactory("CarryTradeVault");
      await expect(VaultFactory.deploy(5001))
        .to.be.revertedWithCustomError({ interface: (await VaultFactory.deploy(3000)).interface }, "HedgeRatioTooHigh")
        .withArgs(5001);
    });
  });

  // ── Deposits ───────────────────────────────────────────────────────────────

  describe("deposit()", () => {
    it("mints shares 1:1 on first deposit", async () => {
      const { vault, alice } = await loadFixture(deployFixture);

      await vault.connect(alice).deposit({ value: DOT(10) });

      expect(await vault.shares(alice.address)).to.equal(DOT(10));
      expect(await vault.totalShares()).to.equal(DOT(10));
      expect(await vault.totalDeposited()).to.equal(DOT(10));
    });

    it("emits Deposited event", async () => {
      const { vault, alice } = await loadFixture(deployFixture);

      await expect(vault.connect(alice).deposit({ value: DOT(5) }))
        .to.emit(vault, "Deposited")
        .withArgs(alice.address, DOT(5), DOT(5));
    });

    it("issues pro-rata shares on subsequent deposits", async () => {
      const { vault, alice, bob } = await loadFixture(deployFixture);

      await vault.connect(alice).deposit({ value: DOT(10) }); // 10 shares for 10 DOT
      await vault.connect(bob).deposit({ value: DOT(5) });   // 5 shares for 5 DOT

      expect(await vault.shares(alice.address)).to.equal(DOT(10));
      expect(await vault.shares(bob.address)).to.equal(DOT(5));
      expect(await vault.totalShares()).to.equal(DOT(15));
      expect(await vault.totalDeposited()).to.equal(DOT(15));
    });

    it("reverts on zero deposit", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      await expect(vault.connect(alice).deposit({ value: 0 }))
        .to.be.revertedWithCustomError(vault, "ZeroDeposit");
    });

    it("reverts in EXECUTING state", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();

      await expect(vault.connect(alice).deposit({ value: DOT(1) }))
        .to.be.revertedWithCustomError(vault, "InvalidState");
    });
  });

  // ── executeCarry ───────────────────────────────────────────────────────────

  describe("executeCarry()", () => {
    async function depositAndCarry() {
      const ctx = await loadFixture(deployFixture);
      await ctx.vault.connect(ctx.alice).deposit({ value: DOT(100) });
      return ctx;
    }

    it("transitions state from IDLE to EXECUTING", async () => {
      const { vault, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      expect(await vault.state()).to.equal(1); // EXECUTING
    });

    it("emits CarryExecuted with correct split (30% hedge)", async () => {
      const { vault, owner } = await depositAndCarry();
      const tx = await vault.connect(owner).executeCarry();
      const receipt = await tx.wait();
      const event = receipt?.logs.find((log: any) => {
        try { return vault.interface.parseLog(log)?.name === "CarryExecuted"; } catch { return false; }
      });
      expect(event).to.not.be.undefined;
      const parsed = vault.interface.parseLog(event as any);
      expect(parsed?.args[0]).to.equal(DOT(70)); // bifrostAmount
      expect(parsed?.args[1]).to.equal(DOT(30)); // hedgeAmount
    });

    it("calls XCM.execute() exactly twice (DOT transfers)", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      expect(await xcm.executeCallCount()).to.equal(2);
    });

    it("calls XCM.send() exactly twice (Transact calls)", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      expect(await xcm.sendCallCount()).to.equal(2);
    });

    it("execute messages contain Bifrost and Hydration para IDs", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      const exec0 = await xcm.getExecuteMsg(0);
      const exec1 = await xcm.getExecuteMsg(1);
      // Bifrost 2001: compact = 0x451F
      expect(exec0.toUpperCase()).to.include("451F");
      // Hydration 2034: compact = 0xC91F
      expect(exec1.toUpperCase()).to.include("C91F");
    });

    it("send messages target Bifrost and Hydration destinations", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      const dest0 = await xcm.getSendDest(0);
      const dest1 = await xcm.getSendDest(1);
      // Bifrost 2001: compact = 0x451F
      expect(dest0.toUpperCase()).to.include("451F");
      // Hydration 2034: compact = 0xC91F
      expect(dest1.toUpperCase()).to.include("C91F");
    });

    it("execute messages start with XCM V5 prefix (0x05)", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      const msg0 = await xcm.getExecuteMsg(0);
      const msg1 = await xcm.getExecuteMsg(1);
      expect(msg0.startsWith("0x05")).to.be.true;
      expect(msg1.startsWith("0x05")).to.be.true;
    });

    it("execute messages contain DepositReserveAsset opcode (0x0E)", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      const msg0 = await xcm.getExecuteMsg(0);
      const msg1 = await xcm.getExecuteMsg(1);
      expect(msg0.toUpperCase()).to.include("0E");
      expect(msg1.toUpperCase()).to.include("0E");
    });

    it("send messages contain Transact opcode (0x06)", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      const msg0 = await xcm.getSendMsg(0);
      const msg1 = await xcm.getSendMsg(1);
      const hex0 = ethers.hexlify(msg0).toUpperCase();
      const hex1 = ethers.hexlify(msg1).toUpperCase();
      expect(hex0).to.include("06");
      expect(hex1).to.include("06");
    });

    it("send messages do NOT contain DepositReserveAsset (no ClearOrigin)", async () => {
      const { vault, xcm, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      // send() messages should use Transact directly, not DepositReserveAsset
      // The 5-instruction pattern: WithdrawAsset(00) BuyExecution(13) Transact(06) RefundSurplus(14) DepositAsset(0D)
      // DepositReserveAsset opcode is 0x0E — it should NOT appear as an instruction opcode
      // (though 0E can appear as data bytes, so we check the message structure instead)
      const msg0 = await xcm.getSendMsg(0);
      const hex0 = ethers.hexlify(msg0);
      // Message starts with 0x05 (V5) + compact(5) = 0x14 (5 instructions)
      expect(hex0.startsWith("0x0514")).to.be.true;
    });

    it("reverts if call templates not set", async () => {
      const [owner, alice] = await ethers.getSigners();
      const VaultFactory = await ethers.getContractFactory("CarryTradeVault");
      const fresh = await VaultFactory.deploy(3000);
      await fresh.setVaultSubstrateAccount(SUBSTRATE_ACCOUNT);
      await fresh.setAssetHubSovereign(ASSET_HUB_SOVEREIGN);
      await fresh.connect(alice).deposit({ value: DOT(10) });

      await expect(fresh.connect(owner).executeCarry())
        .to.be.revertedWithCustomError(fresh, "CallTemplatesNotSet");
    });

    it("reverts if AssetHub sovereign not set", async () => {
      const [owner, alice] = await ethers.getSigners();
      const VaultFactory = await ethers.getContractFactory("CarryTradeVault");
      const fresh = await VaultFactory.deploy(3000);
      await fresh.setCallTemplates(BIFROST_CALL, HYDRATION_CALL);
      await fresh.setVaultSubstrateAccount(SUBSTRATE_ACCOUNT);
      await fresh.connect(alice).deposit({ value: DOT(10) });

      await expect(fresh.connect(owner).executeCarry())
        .to.be.revertedWithCustomError(fresh, "AssetHubSovereignNotSet");
    });

    it("reverts if not in IDLE state", async () => {
      const { vault, owner } = await depositAndCarry();
      await vault.connect(owner).executeCarry();
      await expect(vault.connect(owner).executeCarry())
        .to.be.revertedWithCustomError(vault, "InvalidState");
    });

    it("reverts for non-owner", async () => {
      const { vault, alice } = await depositAndCarry();
      await expect(vault.connect(alice).executeCarry())
        .to.be.revertedWithCustomError(vault, "OwnableUnauthorizedAccount");
    });
  });

  // ── confirmActive ──────────────────────────────────────────────────────────

  describe("confirmActive()", () => {
    it("transitions EXECUTING → ACTIVE", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();
      expect(await vault.state()).to.equal(2); // ACTIVE
    });

    it("emits CarryConfirmed", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await expect(vault.connect(owner).confirmActive())
        .to.emit(vault, "CarryConfirmed");
    });

    it("reverts if not in EXECUTING state", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await expect(vault.connect(owner).confirmActive())
        .to.be.revertedWithCustomError(vault, "InvalidState");
    });
  });

  // ── Withdraw ───────────────────────────────────────────────────────────────

  describe("withdraw()", () => {
    it("returns proportional DOT in IDLE state", async () => {
      const { vault, alice, bob } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(bob).deposit({ value: DOT(10) });

      const balanceBefore = await ethers.provider.getBalance(alice.address);
      const tx = await vault.connect(alice).withdraw(DOT(10));
      const receipt = await tx.wait();
      const gasUsed = receipt!.gasUsed * receipt!.gasPrice;
      const balanceAfter = await ethers.provider.getBalance(alice.address);

      expect(balanceAfter - balanceBefore + gasUsed).to.equal(DOT(10));
    });

    it("emits Withdrawn event", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await expect(vault.connect(alice).withdraw(DOT(10)))
        .to.emit(vault, "Withdrawn")
        .withArgs(alice.address, DOT(10), DOT(10));
    });

    it("reverts if insufficient shares", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(5) });
      await expect(vault.connect(alice).withdraw(DOT(10)))
        .to.be.revertedWithCustomError(vault, "InsufficientBalance");
    });

    it("reverts on zero share amount", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(5) });
      await expect(vault.connect(alice).withdraw(0))
        .to.be.revertedWithCustomError(vault, "ZeroShares");
    });

    it("reverts in EXECUTING state", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await expect(vault.connect(alice).withdraw(DOT(5)))
        .to.be.revertedWithCustomError(vault, "WithdrawNotAllowed");
    });

    it("reverts in ACTIVE state", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();
      await expect(vault.connect(alice).withdraw(DOT(5)))
        .to.be.revertedWithCustomError(vault, "WithdrawNotAllowed");
    });

    it("works after unwindCarry() returns to IDLE", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();

      // Simulate DOT returning from XCM (send DOT to vault)
      await owner.sendTransaction({ to: await vault.getAddress(), value: DOT(10) });
      await vault.connect(owner).unwindCarry();

      // Now withdraw works
      await expect(vault.connect(alice).withdraw(DOT(10))).to.not.be.reverted;
    });
  });

  // ── harvest / yield / unwind ─────────────────────────────────────────────

  describe("harvest()", () => {
    async function setupActive() {
      const ctx = await loadFixture(deployFixture);
      await ctx.vault.connect(ctx.alice).deposit({ value: DOT(100) });
      await ctx.vault.connect(ctx.owner).executeCarry();
      await ctx.vault.connect(ctx.owner).confirmActive();
      return ctx;
    }

    it("sends 2 execute + 1 send XCM calls", async () => {
      const { vault, xcm, owner } = await setupActive();
      // executeCarry already did 2 execute + 2 send
      const execBefore = await xcm.executeCallCount();
      const sendBefore = await xcm.sendCallCount();

      await vault.connect(owner).harvest({ value: DOT(0.1) });

      expect(await xcm.executeCallCount()).to.equal(execBefore + 1n);
      expect(await xcm.sendCallCount()).to.equal(sendBefore + 1n);
    });

    it("emits HarvestInitiated", async () => {
      const { vault, owner } = await setupActive();
      await expect(vault.connect(owner).harvest({ value: DOT(0.1) }))
        .to.emit(vault, "HarvestInitiated");
    });

    it("reverts if not ACTIVE", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await expect(vault.connect(owner).harvest({ value: DOT(0.05) }))
        .to.be.revertedWithCustomError(vault, "InvalidState");
    });

    it("reverts if insufficient fee sent", async () => {
      const { vault, owner } = await setupActive();
      // needs XCM_TRANSFER_FEE (0.01) + XCM_BIFROST_FEE (0.05) = 0.06 DOT
      const tooLowFee = ethers.parseEther("0.05");
      await expect(vault.connect(owner).harvest({ value: tooLowFee }))
        .to.be.revertedWithCustomError(vault, "InsufficientFee");
    });
  });

  describe("recordYield()", () => {
    it("increases totalDeposited (raises share price)", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(100) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();

      const before = await vault.totalDeposited();
      await vault.connect(owner).recordYield(DOT(5));

      expect(await vault.totalDeposited()).to.equal(before + DOT(5));
      expect(await vault.totalYieldHarvested()).to.equal(DOT(5));
    });

    it("emits YieldReceived", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(100) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();

      await expect(vault.connect(owner).recordYield(DOT(5)))
        .to.emit(vault, "YieldReceived")
        .withArgs(DOT(5), DOT(105));
    });

    it("reverts if not ACTIVE", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await expect(vault.connect(owner).recordYield(DOT(5)))
        .to.be.revertedWithCustomError(vault, "InvalidState");
    });
  });

  describe("unwindCarry()", () => {
    it("transitions ACTIVE → IDLE", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();
      await vault.connect(owner).unwindCarry();
      expect(await vault.state()).to.equal(0); // IDLE
    });

    it("emits PositionUnwound", async () => {
      const { vault, alice, owner } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(10) });
      await vault.connect(owner).executeCarry();
      await vault.connect(owner).confirmActive();
      await expect(vault.connect(owner).unwindCarry())
        .to.emit(vault, "PositionUnwound");
    });

    it("reverts if not ACTIVE", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await expect(vault.connect(owner).unwindCarry())
        .to.be.revertedWithCustomError(vault, "InvalidState");
    });
  });

  describe("emergencyRecoverXCM()", () => {
    it("sends XCM to destination", async () => {
      const { vault, xcm, owner } = await loadFixture(deployFixture);
      const sendBefore = await xcm.sendCallCount();

      // Dummy XCM message
      const dummyXcm = ethers.hexlify(ethers.toUtf8Bytes("recovery_xcm"));
      await vault.connect(owner).emergencyRecoverXCM(2001, dummyXcm);

      expect(await xcm.sendCallCount()).to.equal(sendBefore + 1n);
    });

    it("funds AssetHub sovereign when msg.value > 0", async () => {
      const { vault, xcm, owner } = await loadFixture(deployFixture);
      const execBefore = await xcm.executeCallCount();

      const dummyXcm = ethers.hexlify(ethers.toUtf8Bytes("recovery_xcm"));
      await vault.connect(owner).emergencyRecoverXCM(2001, dummyXcm, { value: DOT(0.1) });

      // execute() called for fee transfer + send() for recovery message
      expect(await xcm.executeCallCount()).to.equal(execBefore + 1n);
    });

    it("emits EmergencyXCMSent", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      const dummyXcm = ethers.hexlify(ethers.toUtf8Bytes("recovery_xcm"));
      await expect(vault.connect(owner).emergencyRecoverXCM(2001, dummyXcm))
        .to.emit(vault, "EmergencyXCMSent");
    });

    it("reverts for non-owner", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      const dummyXcm = ethers.hexlify(ethers.toUtf8Bytes("recovery_xcm"));
      await expect(vault.connect(alice).emergencyRecoverXCM(2001, dummyXcm))
        .to.be.revertedWithCustomError(vault, "OwnableUnauthorizedAccount");
    });
  });

  // ── Configuration ──────────────────────────────────────────────────────────

  describe("setHedgeRatio()", () => {
    it("updates hedge ratio", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await vault.connect(owner).setHedgeRatio(4000);
      expect(await vault.hedgeRatioBps()).to.equal(4000);
    });

    it("allows 0% hedge (no hedge)", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await vault.connect(owner).setHedgeRatio(0);
      expect(await vault.hedgeRatioBps()).to.equal(0);
    });

    it("allows max 50% hedge", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await vault.connect(owner).setHedgeRatio(5000);
      expect(await vault.hedgeRatioBps()).to.equal(5000);
    });

    it("reverts above 50%", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await expect(vault.connect(owner).setHedgeRatio(5001))
        .to.be.revertedWithCustomError(vault, "HedgeRatioTooHigh")
        .withArgs(5001);
    });

    it("emits HedgeRatioUpdated", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      await expect(vault.connect(owner).setHedgeRatio(4000))
        .to.emit(vault, "HedgeRatioUpdated")
        .withArgs(3000, 4000);
    });
  });

  describe("setAssetHubSovereign()", () => {
    it("sets AssetHub sovereign account", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      const newAccount = ethers.zeroPadValue(ethers.toBeHex(42), 32);
      await vault.connect(owner).setAssetHubSovereign(newAccount);
      expect(await vault.assetHubSovereign()).to.equal(newAccount);
    });

    it("emits AssetHubSovereignUpdated", async () => {
      const { vault, owner } = await loadFixture(deployFixture);
      const newAccount = ethers.zeroPadValue(ethers.toBeHex(42), 32);
      await expect(vault.connect(owner).setAssetHubSovereign(newAccount))
        .to.emit(vault, "AssetHubSovereignUpdated")
        .withArgs(newAccount);
    });
  });

  // ── View functions ─────────────────────────────────────────────────────────

  describe("View functions", () => {
    it("sharePrice() returns 1e18 for empty vault", async () => {
      const { vault } = await loadFixture(deployFixture);
      expect(await vault.sharePrice()).to.equal(ethers.parseEther("1"));
    });

    it("positionValue() returns correct DOT value", async () => {
      const { vault, alice, bob } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(60) });
      await vault.connect(bob).deposit({ value: DOT(40) });
      expect(await vault.positionValue(alice.address)).to.equal(DOT(60));
      expect(await vault.positionValue(bob.address)).to.equal(DOT(40));
    });

    it("bifrostDeploymentAmount() is 70% of total (with 30% hedge)", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(100) });
      expect(await vault.bifrostDeploymentAmount()).to.equal(DOT(70));
    });

    it("hedgeDeploymentAmount() is 30% of total", async () => {
      const { vault, alice } = await loadFixture(deployFixture);
      await vault.connect(alice).deposit({ value: DOT(100) });
      expect(await vault.hedgeDeploymentAmount()).to.equal(DOT(30));
    });
  });

  // ── XCMBuilder: SCALE encoding ─────────────────────────────────────────────

  describe("XCMBuilder SCALE encoding", () => {
    let encoder: any;

    before(async () => {
      const Factory = await ethers.getContractFactory("XCMBuilderHarness");
      encoder = await Factory.deploy();
    });

    it("compact encodes 0 as 0x00", async () => {
      expect(await encoder.compactEncode(0)).to.equal("0x00");
    });

    it("compact encodes 63 as single byte (63 << 2 = 0xfc)", async () => {
      expect(await encoder.compactEncode(63)).to.equal("0xfc");
    });

    it("compact encodes 64 in two-byte mode", async () => {
      expect(await encoder.compactEncode(64)).to.equal("0x0101");
    });

    it("compact encodes 2001 (Bifrost ParaID)", async () => {
      const result = await encoder.compactEncode(2001);
      expect(result).to.have.length(6); // "0x" + 4 hex chars = 2 bytes
    });

    it("compact encodes 2034 (Hydration ParaID)", async () => {
      const result = await encoder.compactEncode(2034);
      expect(result).to.have.length(6); // 2 bytes in compact mode
    });

    it("compact encodes 1000 (AssetHub ParaID)", async () => {
      // 1000 << 2 | 0x01 = 4001 = 0x0FA1 → LE: 0xA1, 0x0F → "0xa10f"
      const result = await encoder.compactEncode(1000);
      expect(result).to.have.length(6); // 2 bytes
    });

    it("encodeParaDest includes correct XCM V5 prefix (0x05)", async () => {
      const dest = await encoder.encodeParaDest(2001);
      expect(dest.startsWith("0x05")).to.be.true;
    });

    it("encodeDotAssetOnDestination includes Parachain(1000) junction", async () => {
      // Pass 1 DOT in 18-decimal EVM units; the function divides by 1e8 internally
      const asset = await encoder.encodeDotAssetOnDestination(DOT(1));
      const hex = ethers.hexlify(asset).toUpperCase();
      // Should contain compact(AssetHub paraId 1000) = 0xA10F
      expect(hex).to.include("A10F");
    });

    it("encodeDotAsset converts 18-decimal to 10-decimal", async () => {
      // 1 DOT in EVM = 1e18. In Substrate = 1e10 = 10_000_000_000
      const asset = await encoder.encodeDotAsset(DOT(1));
      const hex = ethers.hexlify(asset);
      // compact(10_000_000_000) = big-int mode: 10B > 2^30
      // 10_000_000_000 in hex = 0x2540BE400
      // The encoded amount should be present in the asset bytes
      expect(hex.length).to.be.greaterThan(4); // sanity check — non-trivial encoding
    });
  });

  // ── Pause ──────────────────────────────────────────────────────────────────

  describe("Pause", () => {
    it("pauses deposits", async () => {
      const { vault, owner, alice } = await loadFixture(deployFixture);
      await vault.connect(owner).pause();
      await expect(vault.connect(alice).deposit({ value: DOT(1) }))
        .to.be.revertedWithCustomError(vault, "EnforcedPause");
    });

    it("unpauses correctly", async () => {
      const { vault, owner, alice } = await loadFixture(deployFixture);
      await vault.connect(owner).pause();
      await vault.connect(owner).unpause();
      await expect(vault.connect(alice).deposit({ value: DOT(1) })).to.not.be.reverted;
    });
  });
});
