/**
 * deploy.ts
 *
 * Deploys CarryTradeVault to Polkadot Hub.
 *
 * Usage:
 *   # Testnet
 *   npx hardhat run scripts/deploy.ts --network polkadotHubTest
 *
 *   # Mainnet
 *   npx hardhat run scripts/deploy.ts --network polkadotHub
 *
 * Prerequisites:
 *   1. Set PRIVATE_KEY in .env
 *   2. Run scripts/generateCallBytes.ts to get BIFROST_MINT_CALL and HYDRATION_ROUTER_SELL_CALL
 *   3. Set BIFROST_MINT_CALL, HYDRATION_ROUTER_SELL_CALL, VAULT_SUBSTRATE_ACCOUNT,
 *      ASSET_HUB_SOVEREIGN in .env
 */

import { ethers, network } from "hardhat";
import * as dotenv from "dotenv";

dotenv.config();

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const HEDGE_RATIO_BPS = 3000; // 30% hedge

// Generated by scripts/generateCallBytes.ts
const BIFROST_MINT_CALL        = process.env.BIFROST_MINT_CALL            ?? "";
const HYDRATION_ROUTER_SELL_CALL = process.env.HYDRATION_ROUTER_SELL_CALL ?? "";

// 32-byte substrate account for the vault (receives minted vDOT and trade proceeds)
// Derive this from the deployed contract address after deployment
const VAULT_SUBSTRATE_ACCOUNT = process.env.VAULT_SUBSTRATE_ACCOUNT ?? ethers.ZeroHash;

// 32-byte AssetHub sovereign account on Bifrost/Hydration
// This is blake2_256("sibl" ++ LE(1000)) — same on all sibling parachains
// DOT is deposited here in Step 1 (DepositReserveAsset) and used by Step 2 (Transact)
const ASSET_HUB_SOVEREIGN = process.env.ASSET_HUB_SOVEREIGN ?? ethers.ZeroHash;

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  const [deployer] = await ethers.getSigners();
  const balance = await ethers.provider.getBalance(deployer.address);

  console.log("=".repeat(60));
  console.log(" CarryTradeVault Deployment");
  console.log("=".repeat(60));
  console.log(`Network:   ${network.name} (Chain ID: ${network.config.chainId})`);
  console.log(`Deployer:  ${deployer.address}`);
  console.log(`Balance:   ${ethers.formatEther(balance)} DOT`);
  console.log(`Hedge Ratio: ${HEDGE_RATIO_BPS / 100}%`);
  console.log();

  // ── Deploy ──────────────────────────────────────────────────────────────────
  console.log("Deploying CarryTradeVault...");
  const VaultFactory = await ethers.getContractFactory("CarryTradeVault");
  const vault = await VaultFactory.deploy(HEDGE_RATIO_BPS);
  await vault.waitForDeployment();

  const vaultAddress = await vault.getAddress();
  console.log(`  CarryTradeVault deployed at: ${vaultAddress}`);

  // ── Configure call templates ─────────────────────────────────────────────
  if (BIFROST_MINT_CALL && HYDRATION_ROUTER_SELL_CALL) {
    console.log("\nSetting call templates...");
    const tx = await vault.setCallTemplates(BIFROST_MINT_CALL, HYDRATION_ROUTER_SELL_CALL);
    await tx.wait();
    console.log("  Call templates set");
  } else {
    console.log("\n  Call templates not set (run generateCallBytes.ts first)");
    console.log("    Set BIFROST_MINT_CALL and HYDRATION_ROUTER_SELL_CALL in .env");
  }

  // ── Configure substrate account ──────────────────────────────────────────
  if (VAULT_SUBSTRATE_ACCOUNT !== ethers.ZeroHash) {
    console.log("\nSetting vault substrate account...");
    const tx = await vault.setVaultSubstrateAccount(VAULT_SUBSTRATE_ACCOUNT);
    await tx.wait();
    console.log(`  Substrate account set: ${VAULT_SUBSTRATE_ACCOUNT}`);
  } else {
    console.log("\n  Vault substrate account not set");
    console.log("    Derive it from the contract address and set VAULT_SUBSTRATE_ACCOUNT in .env");
    console.log(`    Contract address (EVM): ${vaultAddress}`);
  }

  // ── Configure AssetHub sovereign ───────────────────────────────────────────
  if (ASSET_HUB_SOVEREIGN !== ethers.ZeroHash) {
    console.log("\nSetting AssetHub sovereign account...");
    const tx = await vault.setAssetHubSovereign(ASSET_HUB_SOVEREIGN);
    await tx.wait();
    console.log(`  AssetHub sovereign set: ${ASSET_HUB_SOVEREIGN}`);
  } else {
    console.log("\n  AssetHub sovereign not set");
    console.log("    Compute blake2_256('sibl' ++ LE(1000)) and set ASSET_HUB_SOVEREIGN in .env");
  }

  // ── Summary ──────────────────────────────────────────────────────────────
  console.log("\n" + "=".repeat(60));
  console.log(" Deployment Summary");
  console.log("=".repeat(60));
  console.log(`Contract:       ${vaultAddress}`);
  console.log(`Owner:          ${deployer.address}`);
  console.log(`Hedge Ratio:    ${HEDGE_RATIO_BPS / 100}%`);
  console.log(`Bifrost Para:   2001`);
  console.log(`Hydration Para: 2034`);
  console.log(`AssetHub Para:  1000`);
  console.log(`XCM Precompile: 0x00000000000000000000000000000000000a0000`);

  if (network.config.chainId === 420420419) {
    console.log(`\nExplorer: https://blockscout.polkadot.io/address/${vaultAddress}`);
  } else if (network.config.chainId === 420420417) {
    console.log(`\nExplorer: https://blockscout-testnet.polkadot.io/address/${vaultAddress}`);
  }

  console.log("\nNext steps:");
  console.log("  1. Derive vault sovereign account (accountId32FromEvm on the contract address)");
  console.log("     Set VAULT_SUBSTRATE_ACCOUNT in .env if not already set");
  console.log("  2. Compute AssetHub sovereign: blake2_256('sibl' ++ LE(1000))");
  console.log("     Set ASSET_HUB_SOVEREIGN in .env if not already set");
  console.log("  3. Generate call bytes with correct DOT amounts:");
  console.log("     DOT_AMOUNT_PLANCK=<amount> npx ts-node scripts/generateCallBytes.ts");
  console.log("  4. Update call templates: vault.setCallTemplates(bifrostCall, hydrationCall)");
  console.log("  5. Deposit DOT: vault.deposit({ value: ethers.parseEther('10') })");
  console.log("  6. Execute carry: vault.executeCarry()");
  console.log("  7. Monitor XCM on Subscan:");
  console.log("     - https://bifrost.subscan.io");
  console.log("     - https://hydration.subscan.io");
  console.log("  8. After confirming XCM success: vault.confirmActive()");
  console.log("\nNo manual pre-funding of sovereign accounts required!");
  console.log("DepositReserveAsset moves DOT atomically in executeCarry().");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
